# This will do biocorecrg/econ_r:0.1
FROM bioconductor/bioconductor_docker:RELEASE_3_14

# File Author / Maintainer
MAINTAINER Luca Cozzuto <lucacozzuto@gmail.com> 

RUN Rscript -e "install.packages(c('tidyverse', 'readr', 'dplyr'))"

RUN Rscript -e "install.packages('argparse')"


